services:
  client:
    image: node:20-slim
    command: ["npm", "run", "dev"]
    working_dir: /project
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true # enable hot reload
    volumes:
      - ./client:/project

  server:
    image: php:8.2-rc-fpm
    command: ["php", "artisan", "serve", "--host=0.0.0.0"]
    working_dir: /project
    ports:
      - 8000:8000
    volumes:
      - ./server:/project
  
  db:
    image: postgres:15.4
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=syugyo
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  
volumes:
  db: {}
